from ubuntu:16.04

RUN apt-get update && apt-get install -y lsb-release && apt-get clean all
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

RUN apt install -y curl 
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && apt-get install -y ros-kinetic-desktop-full

RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
#RUN source ~/.bashrc

RUN apt install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
RUN  apt install python-rosdep
RUN rosdep init
RUN rosdep update

RUN apt-get install -y ros-kinetic-robot-state-publisher ros-kinetic-moveit ros-kinetic-rosbridge-suite ros-kinetic-joy ros-kinetic-ros-control ros-kinetic-ros-controllers ros-kinetic-tf2-web-republisher
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install jsonpickle
RUN mkdir -p /catkin_ws/src
WORKDIR /catkin_ws/src
RUN git clone https://github.com/NiryoRobotics/niryo_one_ros.git .

SHELL ["/bin/bash", "-c", "-l"]
RUN source /opt/ros/kinetic/setup.bash
RUN source /root/.bashrc

WORKDIR /catkin_ws

#RUN /opt/ros/kinetic/bin/catkin_make

#RUN source /root/catkin_ws/devel/setup.bash

